on:
  release:
    types:
      - published

permissions:
  contents: write

env:
  UPSTREAM: LiteLDev/Levilamina
  UPSTREAM_URL: https://github.com/LiteLDev/Levilamina.git

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        target_type:
          - server
          - client
        mode:
          - debug
          - release
    runs-on: windows-latest
    steps:
      - name: Clone repo at release tag
        run: |
          git clone ${{ env.UPSTREAM_URL }} upstream
          cd upstream
          git checkout ${{ github.event.release.tag_name }}

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v6
        with:
          path: |
            ~\AppData\Local\.xmake
          key: xmake-${{ hashFiles('upstream/xmake.lua') }}
          restore-keys: |
            xmake-

      - uses: microsoft/setup-msbuild@v3

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p windows -v -y --target_type=${{ matrix.target_type }} --publish=y
        working-directory: upstream

      - run: |
          xmake -v -y
        working-directory: upstream

      - run: |
          xmake install -o ./sdk
        working-directory: upstream

      - uses: actions/upload-artifact@v7
        with:
          name: levilamina-sdk-${{ github.event.release.tag_name }}-${{ matrix.target_type }}-${{ matrix.mode }}-windows-x64
          path: upstream/sdk/



  upload-to-release:
    needs:
      - build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target_type:
          - server
          - client
        mode:
          - debug
          - release
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: levilamina-sdk-${{ github.event.release.tag_name }}-${{ matrix.target_type }}-${{ matrix.mode }}-windows-x64
          path: artifact

      - run: |
          cd artifact
          zip -r ../levilamina-sdk-${{ github.event.release.tag_name }}-${{ matrix.target_type }}-${{ matrix.mode }}-windows-x64.zip *
        shell: bash

      - uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: |
            levilamina-sdk-${{ github.event.release.tag_name }}-${{ matrix.target_type }}-${{ matrix.mode }}-windows-x64.zip
